#!/usr/bin/env ruby
#^syntax detection
source 'https://supermarket.chef.io'

cookbook 'apache2', '~> 1.8'
cookbook 'iptables-ng', '~> 2.2.0'
cookbook 'nginx', '>= 2.0', '< 2.4.4'
cookbook 'database', '~> 2.0.0'
cookbook 'build-essential', '~> 1.4'

metadata :path => '../../../'

cookbook 'php-fpm'
cookbook 'config-driven-helper-test', :path => '../../cookbooks/config-driven-helper-test'

# Force aws cookbook to not require ohai 2.1.0+, which is incompatible with
# nginx 2.4.x
cookbook 'aws', '< 2.9.0'

# Force iptables to 1.x, as 2.x brings in compat_resource, which is incompatible
# with chef 11.x
cookbook 'iptables', '~> 1.0'

# Make doubly sure that ohai 1.1.x is used instead of 2.1.0+
cookbook 'ohai', '~> 1.1'

cookbook 'rsyslog', '~> 2.2.0'

# Ensure yum::epel is not required by nginx by forcing a requirement for 3.x
cookbook 'yum', '>= 3.0'