#!/usr/bin/env ruby
#^syntax detection
source 'https://api.berkshelf.com'

cookbook 'apache2', '~> 3.2'
cookbook 'iptables-ng', '~> 2.2'
cookbook 'nginx', '= 2.4.2'
cookbook 'database', '~> 2.0.0'
cookbook 'build-essential', '~> 1.4'

metadata :path => '../../../'

cookbook 'php-fpm'
cookbook 'config-driven-helper-test', :path => '../../cookbooks/config-driven-helper-test'